# Generated by Django 4.1.7 on 2023-06-11 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=40)),
                ('patronimyc', models.CharField(blank=True, max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_clerk', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('conference_range', models.CharField(choices=[('high', 'Международный уровень'), ('middle', 'Всероссийский уровень'), ('low', 'Региональный уровень')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('research_title', models.CharField(max_length=200)),
                ('points1', models.FloatField()),
                ('points2', models.FloatField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('research_area', models.CharField(choices=[('physics', 'Физико-технический'), ('math', 'Математика и ИТ'), ('bio', 'Биолого-экологический'), ('chemistry', 'Химико-технический'), ('language', 'Лингвистический')], max_length=50)),
            ],
            options={
                'verbose_name': 'Научная работа',
                'verbose_name_plural': 'Научные работы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(null=True)),
                ('conferences', models.ManyToManyField(blank=True, related_name='student_conferences', to='backend.conference', verbose_name='конференции')),
                ('researches', models.ManyToManyField(blank=True, related_name='student_researches', to='backend.research', verbose_name='научные работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учащийся',
                'verbose_name_plural': 'Учащиеся',
            },
        ),
        migrations.AddField(
            model_name='research',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher'),
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, null=True)),
                ('position', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
