# Generated by Django 4.1.7 on 2023-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="research_area",
            field=models.CharField(
                choices=[
                    ("physics", "Физико-технический"),
                    ("math", "Математика и ИТ"),
                    ("bio", "Биолого-экологический"),
                    ("chemistry", "Химико-технический"),
                    ("language", "Лингвистический"),
                ],
                max_length=50,
            ),
        ),
    ]
