# Generated by Django 4.1.7 on 2023-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='research_title',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
