# Generated by Django 4.1.7 on 2023-06-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='descrition',
            new_name='description',
        ),
    ]
