# Generated by Django 4.1.7 on 2023-06-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_research_research_area"),
        ("backend", "0002_rename_descrition_conference_description"),
    ]

    operations = []
