# Generated by Django 4.1.7 on 2023-06-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_merge_20230610_2041"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="points1",
        ),
        migrations.RemoveField(
            model_name="student",
            name="points2",
        ),
        migrations.RemoveField(
            model_name="student",
            name="score",
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("research_title", models.CharField(max_length=200)),
                ("points1", models.FloatField()),
                ("points2", models.FloatField()),
                ("score", models.PositiveIntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teacher",
                    ),
                ),
            ],
        ),
    ]
