# Generated by Django 4.1.7 on 2023-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_remove_student_points1_remove_student_points2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="student",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="report",
            name="teacher",
            field=models.CharField(max_length=200),
        ),
    ]
