# Generated by Django 4.1.7 on 2023-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_report_student_alter_report_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="clerk",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="clerk",
            name="position",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="position",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
